### ISSUE TITLE
Clap does not emit help-message on no-args

### ISSUE THREAD

**Issue by falkecarlsen** [d702e20/CGAAL#108]
Using https://docs.rs/clap/2.33.3/clap/struct.App.html#method.print_help is not a viable route as App is consumed upon using get_matches, making it difficult to call print_help after using the result of get_matches to check if subcommands exist.

Could be solved by using the setting AppSettings::ArgRequiredElseHelp (https://docs.rs/clap/2.31.1/clap/enum.AppSettings.html#variant.ArgRequiredElseHelp), however there's issues with subcommands counting as arguments and if any default values are set (e.g. log-level), this effectively negates this setting.

This is a low value fix that seems difficult to implement. Found during #102.

**Comment by NicEastvillage** [comment]
Resolved in #224. The setting we needed was called `AppSettings::SubcommandRequiredElseHelp`.
