### ISSUE TITLE
In need of a logo

### ISSUE THREAD

**Issue by MathiasMehl** [d702e20/CGAAL#172]
We are in desperate need of a logo, we should get one, such that people can more easily distinguish our model checker from others

**Comment by NicEastvillage** [comment]
Here we go!

![logo](https://user-images.githubusercontent.com/21122471/135886696-f86063f1-d026-420c-b2bc-8d2735a23f4c.png)

**Comment by NicEastvillage** [comment]
On a more serious note... I made these sketches. Whadya think? Maybe with colors?
![image](https://github.com/d702e20/CGAAL/assets/21122471/9539e084-3896-4ba9-851b-2cd3b7e9b121)

**Comment by NicEastvillage** [comment]
This font makes it extra classy
![billede](https://github.com/d702e20/CGAAL/assets/21122471/d7806f71-8243-44ac-916e-d4d3f7ec6c91)

**Comment by NicEastvillage** [comment]
We are very close now
![birds in hexex with text CGAAL](https://github.com/d702e20/CGAAL/assets/21122471/aa0138f3-17da-43cb-92b7-690f2c28c2f3)

**Comment by falkecarlsen** [comment]
> We are very close now ![birds in hexex with text CGAAL](https://user-images.githubusercontent.com/21122471/266773574-aa0138f3-17da-43cb-92b7-690f2c28c2f3.png)

Let's roll with that one
