### ISSUE TITLE
Since at least 5fefb911 some test_dcz_* fails non-deterministically

### ISSUE THREAD

**Issue by falkecarlsen** [d702e20/CGAAL#186]
Seems it's any of the:
- algorithms::certain_zero::test::test_dcz_general_*
- algorithms::certain_zero::test::test_dcz_negation_*

See also this GA-job: https://github.com/d702e20/CGAAL/actions/runs/5153268985/jobs/9280298488

**Comment by NicEastvillage** [comment]
So since #183, some test are crashing? or is it wrong answers?
